#!/bin/bash

# H3 Index Assessment Script
# Runs all checks and generates report

set -e

echo "========================================================================="
echo "  H3 Index Assessment - PinPoint India"
echo "========================================================================="
echo ""
echo "This script will:"
echo "  1. Check Redis H3 index status"
echo "  2. Check PostgreSQL/PostGIS capabilities"
echo "  3. Generate summary report"
echo ""
echo "Results will be saved to:"
echo "  - H3_INDEX_STATUS_BEFORE.txt"
echo "  - DATABASE_STATUS.txt"
echo "  - H3_ASSESSMENT_SUMMARY.txt"
echo ""
read -p "Press ENTER to continue or Ctrl+C to cancel..."
echo ""

# Create output directory
mkdir -p assessment-reports
cd assessment-reports

echo "========================================================================="
echo "Step 1: Checking Redis H3 Index Status"
echo "========================================================================="
echo ""

if [ -f ../scripts/check-redis-h3-index.sh ]; then
  echo "Running Redis check..."
  bash ../scripts/check-redis-h3-index.sh | tee H3_INDEX_STATUS_BEFORE.txt
  echo ""
  echo "✅ Redis status saved to: assessment-reports/H3_INDEX_STATUS_BEFORE.txt"
else
  echo "⚠️  check-redis-h3-index.sh not found, using TypeScript version..."
  cd ..
  npm run build 2>/dev/null
  node dist/scripts/check-redis-status.js | tee assessment-reports/H3_INDEX_STATUS_BEFORE.txt
  cd assessment-reports
  echo ""
  echo "✅ Redis status saved to: assessment-reports/H3_INDEX_STATUS_BEFORE.txt"
fi

echo ""
echo "========================================================================="
echo "Step 2: Checking PostgreSQL/PostGIS Capabilities"
echo "========================================================================="
echo ""

if [ -f ../scripts/check-database-capabilities.sh ]; then
  echo "Running database check..."
  bash ../scripts/check-database-capabilities.sh | tee DATABASE_STATUS.txt
  echo ""
  echo "✅ Database status saved to: assessment-reports/DATABASE_STATUS.txt"
else
  echo "⚠️  check-database-capabilities.sh not found, using TypeScript version..."
  cd ..
  npm run build 2>/dev/null
  node dist/scripts/check-postgres-capabilities.js | tee assessment-reports/DATABASE_STATUS.txt
  cd assessment-reports
  echo ""
  echo "✅ Database status saved to: assessment-reports/DATABASE_STATUS.txt"
fi

echo ""
echo "========================================================================="
echo "Step 3: Generating Summary Report"
echo "========================================================================="
echo ""

# Generate summary
cat > H3_ASSESSMENT_SUMMARY.txt << 'EOF'
# H3 Index Assessment Summary
Date: $(date)

## Redis Status
$(cat H3_INDEX_STATUS_BEFORE.txt | grep -A 5 "H3 Index Metadata" || echo "No metadata found")

## Database Status
$(cat DATABASE_STATUS.txt | grep -A 10 "ASSESSMENT SUMMARY" || echo "No summary found")

## Key Findings

### Redis H3 Index
- Total keys: $(cat H3_INDEX_STATUS_BEFORE.txt | grep "Total keys in database" | awk '{print $5}')
- Memory used: $(cat H3_INDEX_STATUS_BEFORE.txt | grep "Memory used" | awk '{print $3}')

### PostgreSQL H3 Extension
$(cat DATABASE_STATUS.txt | grep "H3 EXTENSION" || echo "Status unknown")

## Recommendations

Based on the assessment:

1. If H3 extension IS available:
   → Proceed with native h3_polygon_to_cells() approach

2. If H3 extension NOT available (expected on Railway):
   → Implement hybrid JavaScript + PostGIS ST_Intersects approach
   → See: pynpoint/MIGRATION_H3_POSTGIS.md (Option B)

## Next Steps

1. Review the three generated reports
2. Confirm H3 extension availability
3. Choose implementation approach
4. Proceed with implementation

---
Generated by: pynpoint/scripts/run-h3-assessment.sh
EOF

echo "✅ Summary report saved to: assessment-reports/H3_ASSESSMENT_SUMMARY.txt"
echo ""

echo "========================================================================="
echo "Assessment Complete!"
echo "========================================================================="
echo ""
echo "Reports generated:"
echo "  1. assessment-reports/H3_INDEX_STATUS_BEFORE.txt"
echo "  2. assessment-reports/DATABASE_STATUS.txt"
echo "  3. assessment-reports/H3_ASSESSMENT_SUMMARY.txt"
echo ""
echo "Next steps:"
echo "  1. Review the reports"
echo "  2. Check if H3 extension is available on Railway"
echo "  3. If not available, proceed with Option B (hybrid approach)"
echo ""
echo "For implementation guidance, see:"
echo "  - H3_INDEX_SITUATION_ANALYSIS.md"
echo "  - pynpoint/MIGRATION_H3_POSTGIS.md"
echo ""
